bot:
  token: ${BOT_TOKEN}
  username: list_of_titles_bot

spring:
  security:
    filter:
      order: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/list_of_titles
    username: root
    password: vladgo!2003

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: info
    org.hibernate.type: info
